# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Ops', [dirname(__file__)])
        except ImportError:
            import _Ops
            return _Ops
        if fp is not None:
            try:
                _mod = imp.load_module('_Ops', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Ops = swig_import_helper()
    del swig_import_helper
else:
    import _Ops
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Ops(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Ops, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Ops, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _Ops.new_Ops(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Ops.delete_Ops
    __del__ = lambda self : None;
    def mkdir(self, *args): return _Ops.Ops_mkdir(self, *args)
    def rmdir(self, *args): return _Ops.Ops_rmdir(self, *args)
    def read(self, *args): return _Ops.Ops_read(self, *args)
    def readLocal(self, *args): return _Ops.Ops_readLocal(self, *args)
    def write(self, *args): return _Ops.Ops_write(self, *args)
    def remove(self, *args): return _Ops.Ops_remove(self, *args)
    def dump(self, *args): return _Ops.Ops_dump(self, *args)
    def dumpLocal(self, *args): return _Ops.Ops_dumpLocal(self, *args)
    def list(self, *args): return _Ops.Ops_list(self, *args)
    def makeLeader(self): return _Ops.Ops_makeLeader(self)
    def getLeader(self): return _Ops.Ops_getLeader(self)
    def reconfigure(self, *args): return _Ops.Ops_reconfigure(self, *args)
Ops_swigregister = _Ops.Ops_swigregister
Ops_swigregister(Ops)

# This file is compatible with both classic and new-style classes.


