Import('env', 'object_files')

libs = [ "pthread", "protobuf", "rt", "cryptopp" ]

src = [
    "Ops.cc"
]
object_files['Impl'] = env.StaticObject(src)

env.Default([
    env.SharedLibrary("Ops", ['Ops.cc'],
                LIBS = libs)
])
