Import('env','object_files')

libs = [ "pthread", "protobuf", "rt", "cryptopp" ]

object_files['Ops'] = env.SharedObject(["Ops.cc"])

env.Default([

    #env.SharedLibrary("Ops", ["Ops.cc", "Ops.i", "#build/logcabin.so"],
     #           LIBS = ""),

    env.Program("Benchmark",
                ["Benchmark.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("Ops",
                ["Ops_test.cc", "Ops.cc","#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("FailoverTest",
                ["FailoverTest.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("HelloWorld",
                ["HelloWorld.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("Reconfigure",
                ["Reconfigure.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("ReconfigureTest",
                ["ReconfigureTest.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("SmokeTest",
                ["SmokeTest.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("TreeOps",
                ["TreeOps.cc", "#build/liblogcabin.a"],
                LIBS = libs),
])
